---
- name: Wait 3 minutes and then from localhost poll every 30 seconds for 10 minutes to check if port 22 on {{ ansible_hostname }} with ip {{ ansible_host }} is active and contain "OpenSSH"
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    timeout: 600
    delay: 180
    sleep: 30
  delegate_to: "{{ pi_jumphost }}"
  vars:
    ansible_user: "{{ lookup('env','PI_USERNAME') }}"
    ansible_ssh_pass: "{{ lookup('env','PI_PASSWORD') }}"
