---
- name: set admin password
  raw: set user admin password-hash {{gaia_admin_pwd_hash}}
  vars:
    ansible_ssh_pass: admin  # This is the default installation passord in GAIA, it is fine to have them in clear text
  #delegate_to: "{{ hostvars['jumphost1'].ansible_host }}"