---
- name: Wait 300 seconds for port 22 on {{ ansible_host }} to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    delay: 10
  delegate_to: "{{ hostvars['jumphost1'].ansible_host }}"
  vars:
    - ansible_user: "{{ lookup('env','PI_USERNAME') }}"
    - ansible_ssh_pass: "{{ lookup('env','PI_PASSWORD') }}"
