# Main tasks file for mho_reset
---
- name: Reset to factory defaut on {{ ansible_hostname }}
  ignore_errors: yes
  raw: "{{ item }}"
  with_items:
    - clish -c 'lock database override'
    - clish -c 'set fcd revert Gaia_R80.20SP'

---
- name: Wait 3 minutes and then poll every 10 second for 5 minutes to check if port 22 on {{ ansible_host }} is active and contain "OpenSSH"
  wait_for:
    port: 22
    host: "{{ mho_default_ip }}"
    search_regex: OpenSSH
    delay: 180
    sleep: 10
  #connection: local 
  delegate_to: "{{ hostvars['MiniRack5Pi'].ansible_host }}"

