# Main tasks file for build_inventory
---
- name: Add Maestro Hypervisor Orchestrator (MHO) hosts accessed through jumphost to inventory.
  add_host:
    hostname: jump.to.{{ item.hostname }}
    ansible_hostname: "{{ item.hostname }}"
    ansible_host: "{{ item.ansible_host}}"
    mho_def_gw: "{{ item.mho_def_gw}}"
    mho_port_num: "{{ item.mho_port_num}}"
    new_ip: "{{ item.new_ip }}"
    groups:
      - jump.to.mho
    ansible_user: "{{ lookup('env','MHO_ADMIN') }}"
    ansible_ssh_pass: "{{ lookup('env','MHO_ADMIN_PASSWORD') }}"
    ansible_python_interpreter: "{{ lookup('env','MHO_PYTHON_INTERPRETER') }}"
    ansible_ssh_common_args: -o ProxyCommand="sshpass -p '{{ lookup('env','PI_PASSWORD') }}' ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -W %h:%p -q {{ lookup('env','PI_USERNAME') }}@{{ item.pi_jumphost }} -p 22"
  with_items:
  - { hostname: "{{ lookup('env','MINIRACK5_MHO1_HOSTNAME') }}", ansible_host: "{{ lookup('env','MHO_DEFAULT_IP') }}", pi_jumphost: "{{ lookup('env','MINIRACK5_JUMPHOST') }}", new_ip: "{{ lookup('env','MINIRACK5_MHO1_IP') }}", mho_def_gw: "{{ lookup('env','MINIRACK5_Default_Route') }}", mho_port_num: "{{ lookup('env','MINIRACK5_MHO1_Port') }}" }
  - { hostname: "{{ lookup('env','MINIRACK5_MHO2_HOSTNAME') }}", ansible_host: "{{ lookup('env','MHO_DEFAULT_IP') }}", pi_jumphost: "{{ lookup('env','MINIRACK5_JUMPHOST') }}", new_ip: "{{ lookup('env','MINIRACK5_MHO2_IP') }}", mho_def_gw: "{{ lookup('env','MINIRACK5_Default_Route') }}", mho_port_num: "{{ lookup('env','MINIRACK5_MHO2_Port') }}"  }
  - { hostname: "{{ lookup('env','MINIRACK13_MHO1_HOSTNAME') }}", ansible_host: "{{ lookup('env','MHO_DEFAULT_IP') }}", pi_jumphost: "{{ lookup('env','MINIRACK13_JUMPHOST') }}", new_ip: "{{ lookup('env','MINIRACK13_MHO1_IP') }}", mho_def_gw: "{{ lookup('env','MINIRACK13_Default_Route') }}", mho_port_num: "{{ lookup('env','MINIRACK13_MHO1_Port') }}"  }
  - { hostname: "{{ lookup('env','MINIRACK13_MHO2_HOSTNAME') }}", ansible_host: "{{ lookup('env','MHO_DEFAULT_IP') }}", pi_jumphost: "{{ lookup('env','MINIRACK13_JUMPHOST') }}", new_ip: "{{ lookup('env','MINIRACK13_MHO2_IP') }}", mho_def_gw: "{{ lookup('env','MINIRACK13_Default_Route') }}", mho_port_num: "{{ lookup('env','MINIRACK13_MHO2_Port') }}"   }
  - { hostname: "{{ lookup('env','DEMOLAB_MHO1_HOSTNAME') }}", ansible_host: "{{ lookup('env','MHO_DEFAULT_IP') }}", pi_jumphost: "{{ lookup('env','DEMOLAB_JUMPHOST') }}", new_ip: "{{ lookup('env','DEMOLAB_MHO1_IP') }}", mho_def_gw: "{{ lookup('env','DEMOLAB_Default_Route') }}", mho_port_num: "{{ lookup('env','DEMOLAB_MHO1_Port') }}" }
  - { hostname: "{{ lookup('env','DEMOLAB_MHO2_HOSTNAME') }}", ansible_host: "{{ lookup('env','MHO_DEFAULT_IP') }}", pi_jumphost: "{{ lookup('env','DEMOLAB_JUMPHOST') }}", new_ip: "{{ lookup('env','DEMOLAB_MHO2_IP') }}", mho_def_gw: "{{ lookup('env','DEMOLAB_Default_Route') }}", mho_port_num: "{{ lookup('env','DEMOLAB_MHO2_Port') }}" }

- name: Add Maestro Hypervisor Orchestrator (MHO) hosts to inventory
  add_host:
    hostname: "{{ item.hostname }}"
    ansible_hostname: "{{ item.hostname }}"
    ansible_host: "{{ item.ansible_host }}"
    pi_jumphost: "{{ item.pi_jumphost }}"
    mho_port_num: "{{ item.mho_port_num}}"
    groups:
      - mho
    ansible_user: "{{ lookup('env','MHO_ADMIN') }}"
    ansible_ssh_pass: "{{ lookup('env','MHO_ADMIN_PASSWORD') }}"
    ansible_python_interpreter: "{{ lookup('env','MHO_PYTHON_INTERPRETER') }}"
  with_items:
  - { hostname: "{{ lookup('env','MINIRACK5_MHO1_HOSTNAME') }}", ansible_host: "{{ lookup('env','MINIRACK5_MHO1_IP') }}", pi_jumphost: "{{ lookup('env','MINIRACK5_JUMPHOST') }}", mho_port_num: "{{ lookup('env','MINIRACK5_MHO1_Port') }}" }
  - { hostname: "{{ lookup('env','MINIRACK5_MHO2_HOSTNAME') }}", ansible_host: "{{ lookup('env','MINIRACK5_MHO2_IP') }}", pi_jumphost: "{{ lookup('env','MINIRACK5_JUMPHOST') }}", mho_port_num: "{{ lookup('env','MINIRACK5_MHO2_Port') }}" }
  - { hostname: "{{ lookup('env','MINIRACK13_MHO1_HOSTNAME') }}", ansible_host: "{{ lookup('env','MINIRACK13_MHO1_IP') }}", pi_jumphost: "{{ lookup('env','MINIRACK13_JUMPHOST') }}", mho_port_num: "{{ lookup('env','MINIRACK13_MHO1_Port') }}" }
  - { hostname: "{{ lookup('env','MINIRACK13_MHO2_HOSTNAME') }}", ansible_host: "{{ lookup('env','MINIRACK13_MHO2_IP') }}", pi_jumphost: "{{ lookup('env','MINIRACK13_JUMPHOST') }}", mho_port_num: "{{ lookup('env','MINIRACK13_MHO2_Port') }}" }
  - { hostname: "{{ lookup('env','DEMOLAB_MHO1_HOSTNAME') }}", ansible_host: "{{ lookup('env','DEMOLAB_MHO1_IP') }}", pi_jumphost: "{{ lookup('env','DEMOLAB_JUMPHOST') }}", mho_port_num: "{{ lookup('env','DEMOLAB_MHO1_Port') }}" }
  - { hostname: "{{ lookup('env','DEMOLAB_MHO2_HOSTNAME') }}", ansible_host: "{{ lookup('env','DEMOLAB_MHO2_IP') }}", pi_jumphost: "{{ lookup('env','DEMOLAB_JUMPHOST') }}", mho_port_num: "{{ lookup('env','DEMOLAB_MHO2_Port') }}" }

- name: Add Rasberry PI jump hosts to inventory
  add_host:
    hostname: "{{ item.hostname }}"
    ansible_hostname: "{{ item.hostname }}"
    ansible_host: "{{ item.ansible_host }}"
    #mho_default_ip: "{{ lookup('env','MHO_DEFAULT_IP') }}"
    groups: jumphost
    ansible_user: "{{ lookup('env','PI_USERNAME') }}"
    ansible_ssh_pass: "{{ lookup('env','PI_PASSWORD') }}"
  with_items:
  - { hostname: MiniRack5Pi, ansible_host: "{{ lookup('env','MINIRACK5_JUMPHOST') }}" }
  - { hostname: MiniRack13Pi, ansible_host: "{{ lookup('env','MINIRACK13_JUMPHOST') }}" }
  - { hostname: DemolabPi, ansible_host: "{{ lookup('env','DEMOLAB_JUMPHOST') }}" }
