---
# Run with extra vars for example: 
## ansible-playbook MHO-reset.yml -e "target=MiniRack5-MHO1"
# Avaliable Options 
## target= MiniRack5-MHO1, MiniRack5-MHO2, MiniRack13-MHO1, MiniRack13-MHO2, Demolab-MHO1, Demolab-MHO2
- name: Build a dynamic inventory
  tags: always 
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - role: ../roles/build_inventory

- name:  Reset MHO to factory default on "{{ target }}"
  hosts: "{{ target }}"
  gather_facts: no
  roles:
  - role: ../roles/mho_reset

- name:  Initial configuration of "{{ target }}" through jumphost
  hosts: jump.to.{{ target }}
  gather_facts: no
  roles:
  - role: ../roles/mho_initial_config

- name:  Import and install update or JHF on "{{ target }}"
  hosts: "{{ target }}"
  gather_facts: no
  roles:
   - role: ../roles/mho_update_and_install 

- name:  Set maestro configuration on "{{ target }}"
  hosts: "{{ target }}"
  gather_facts: no
  roles:
  - role: ../roles/mho_maestro_config
