---
- name: Build a dynamic inventory
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - role: ../roles/build_inventory



- name:  Initial configuration
  hosts: mho-default-ip
  gather_facts: no
  roles:
  - role: ../roles/mho_initial_config