---
- name: Build a dynamic inventory
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - role: ../roles/build_inventory

- name:  Initial configuration through minirack jumphost
  hosts: jump.to.mho
  gather_facts: no
  roles:
  - role: ../roles/mho_initial_config

- name:  Import and install JHF on MHO
  hosts: mho
  gather_facts: no
  roles:
  - role: ../roles/mho_install_jhf  